// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_freq_w_similarity
NumericMatrix rcpp_freq_w_similarity(NumericMatrix mat, NumericVector freq1);
RcppExport SEXP _GGNet_rcpp_freq_w_similarity(SEXP matSEXP, SEXP freq1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type freq1(freq1SEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_freq_w_similarity(mat, freq1));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GGNet_rcpp_freq_w_similarity", (DL_FUNC) &_GGNet_rcpp_freq_w_similarity, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_GGNet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
